# Generated by Django 4.2.1 on 2024-07-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('duration', models.FloatField()),
                ('resolution', models.CharField(max_length=10)),
                ('background_color', models.CharField(max_length=7)),
                ('font_color', models.CharField(max_length=7)),
                ('font_scale', models.FloatField()),
                ('thickness', models.IntegerField()),
                ('include_stripe', models.BooleanField(default=False)),
                ('stripe_color', models.CharField(blank=True, max_length=7, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
